Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

admin.site.site_header = "Log in to Shihab's Portfolio"
admin.site.site_title = "Shihab's Portfolio Admin Panel"
admin.site.index_title = "Welcome to Shihab's Portfolio Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),

    path('profile/', user_views.profile, name='profile'),

    path('signup/', user_views.registration, name='registration'),
    path('login/', user_views.login_user, name='login'),
    path('logout/', user_views.logout_user, name='logout'),

    path('password-change/', user_views.password_change, name='password_change'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'),
    #      name='change_password'),
    # path('password-change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
    #      name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('', views.base_home, name='base-home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('inbox/', views.inbox_page, name='inbox'),
    path('message/<str:pk>/', views.message_page, name='message'),
    path('reply/<str:pk>/', views.message_reply, name='message-reply'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_home, name='blog-home'),
    path('post/new/', views.post_create, name='post-create'),
    path('user/<str:username>/', views.user_posts, name='user-posts'),
    path('post/<slug:slug>/', views.post_details, name='post-details'),
    path('post/update/<slug:slug>/', views.post_update, name='post-update'),
    path('post/delete/<slug:slug>/', views.post_delete, name='post-delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
import uuid
from django.utils import timezone
from django.utils.text import slugify


class Category(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Post(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    sub_heading = models.CharField(max_length=500, null=True, blank=True)
    content = RichTextUploadingField()
    thumbnail = models.ImageField(upload_to='blog/thumbnails', default='blog/thumbnails/thumbnail.png',
                                  null=True, blank=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)
    categories = models.ManyToManyField(Category)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return f'{self.title} by {self.author}'

    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url

    def save(self, *args, **kwargs):
        if self.slug is None:
            slug = slugify(self.title)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.title) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created']


class PostComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.comment[:30]} by {self.author}'

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        labels = {'sub_heading': 'Sub Heading'}
        widgets = {
            'categories': forms.CheckboxSelectMultiple()
        }
        exclude = ['author', 'created', 'featured', 'slug']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .filters import PostFilter
from .forms import PostForm
from .models import Post, PostComment


def blog_home(request):
    posts = Post.objects.filter(active=True)

    my_filter = PostFilter(request.GET, queryset=posts)
    posts = my_filter.qs

    page = request.GET.get('page')

    paginator = Paginator(posts, 5)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'my_filter': my_filter}
    return render(request, 'blog/blog_home.html', context)


def post_details(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == 'POST':
        comment = request.POST.get('comment')

        if len(comment) == 0:
            return redirect('blog:post-details', slug=post.slug)

        PostComment.objects.create(author=request.user, post=post, comment=comment)
        messages.success(request, "You're comment was successfully posted!")

        return redirect('blog:post-details', slug=post.slug)

    # posts = Post.objects.filter(active=True, featured=True).exclude(title=post.title)[:3]
    posts = Post.objects.filter(active=True, featured=True)[:3]

    context = {'post': post, 'posts': posts}
    return render(request, 'blog/post_details.html', context)


def user_posts(request, username):
    user = get_object_or_404(User, username=username)

    posts = Post.objects.filter(active=True, author=user)

    my_filter = PostFilter(request.GET, queryset=posts)
    posts = my_filter.qs

    page = request.GET.get('page')

    paginator = Paginator(posts, 5)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'my_filter': my_filter, 'user': user}
    return render(request, 'blog/user_posts.html', context)


@login_required
def post_create(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            instance = form.save()
            return redirect('blog:post-details', slug=instance.slug)

    context = {'form': form, 'section_title': 'Add Post'}
    return render(request, 'blog/post_form.html', context)


@login_required
def post_update(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if post.author == request.user:
        form = PostForm(instance=post)

        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                instance = form.save()
                messages.success(request, f'Post updated')
                return redirect('blog:post-details', slug=instance.slug)

        context = {'form': form, 'section_title': 'Update Post'}
        return render(request, 'blog/post_form.html', context)
    else:
        return HttpResponse('You are not authorized to edit this post.')


@login_required
def post_delete(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if post.author == request.user:
        if request.method == 'POST':
            post.delete()
            messages.success(request, f'Post deleted successfully')
            return redirect('blog:blog-home')

        context = {'post': post}
        return render(request, 'blog/post_confirm_delete.html', context)
    else:
        return HttpResponse('You are not authorized to delete this post.')

blog/templates/blog/blog_home.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block blogactive %} active {% endblock blogactive %}

{% block body %}

<main id="main">
    <section id="blog-post" class="blog-post">
        <div class="container">

            <div class="section-title">
                <h2>Posts</h2>
            </div>

            <div class="row post-container justify-content-center">

                <div class="col-lg-4 col-md-4">
                    <form id="searchForm" method="GET" class="p-4 bg-light border shadow-sm">
		                {{ my_filter.form|crispy }}

		                <input class="btn btn-outline-primary mt-2" type="submit" value="Search">
	                </form>
                </div>

                <div class="col-lg-8 col-md-8 post-item">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %}
                    {% endif %}

                    {% for post in posts %}
                    <div class="card mb-3 box" style="margin:auto;">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="card-body">
                                    <div class="border-bottom">
                                        <strong class="d-inline-block mb-1 me-2 text-primary">
                                            <a href="{% url 'blog:user-posts' post.author %}">{{ post.author }}</a>
                                        </strong>
                                        <small class="text-muted me-2">{{ post.created|date:"F d, Y" }}</small>
                                        {% if post.author == request.user %}
                                            <a class="btn btn-secondary btn-sm mb-1 me-2" role="button"
                                            href="{% url 'blog:post-update' post.slug %}">Update</a>
                                            <a class="btn btn-danger btn-sm mb-1" role="button"
                                            href="{% url 'blog:post-delete' post.slug %}">Delete</a>
                                        {% endif %}
                                    </div>
                                    <h3 class="my-3">
                                        <a href="{% url 'blog:post-details' post.slug %}">{{ post.title }}</a>
                                    </h3>

                                    <p class="article-content mt-4">{{ post.sub_heading|truncatechars:300 }}</p>
                                </div>
                            </div>

                            <div class="col-md-4 img-box">
                                <img src="{{ post.imageURL }}" class="card-img" alt="..." height="200px">
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="mt-4">
                        <h3 class="text-center">No Posts available.</h3>
                    </div>
                    {% endfor %}

                    <div class="row my-4">
                        <div>
                            {% include 'blog/pagination.html' %}
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </section>

</main>

{% endblock body %}

blog/templates/blog/pagination.html
{% if posts.has_other_pages %}

    {% if posts.has_previous %}
		<a data-page="1" href="?page=1" class="btn btn-outline-info paginator-link">First</a>
		<a data-page="{{ posts.previous_page_number }}" href="?page={{ posts.previous_page_number }}"
		   class="btn btn-outline-info paginator-link">Previous</a>
	{% endif %}

	{% for num in posts.paginator.page_range %}
		{% if posts.number == num %}
			<a class="btn btn-info paginator-link">{{ num }}</a>
		{% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
			<a data-page="{{ num }}" href="?page={{ num }}" class="btn btn-outline-info paginator-link">{{ num }}</a>
		{% endif %}

	{% endfor %}

	{% if posts.has_next %}
		<a data-page="{{ posts.next_page_number }}" href="?page={{ posts.next_page_number }}"
		   class="btn btn-outline-info paginator-link">Next</a>
		<a data-page="{{ posts.paginator.num_pages }}" href="?page={{ posts.paginator.num_pages }}"
		   class="btn btn-outline-info paginator-link">Last</a>
    {% endif %}

{% endif %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base/base.html' %}

{% block body %}

<main id="main">
    <section id="post-delete" class="post-delete">
        <div class="container">

            <div class="section-title">
                <h2>Delete Post</h2>
            </div>

            <div class="row justify-content-center">
                <div class="col-lg-10 p-4 text-center">
                    <form method="post"> {% csrf_token %}
                        <fieldset>
                            <h3>Are you sure you want to delete the post "{{ post.title }}"?</h3>
                        </fieldset>
                        <div class="mt-4">
                            <button class="btn btn-delete me-2" type="submit">Yes, Delete</button>
                            <a class="btn btn-cancel" href="{% url 'blog:blog-home' %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </section>
</main>

{% endblock body %}

blog/templates/blog/post_details.html
{% extends 'base/base.html' %}

{% block body %}
{% load humanize %}

<main id="main">
    <section id="post-details" class="post-details">
        <div class="container">
            <div class="row justify-content-center">

                <div class="col-lg-8 post-content-wrapper">
                    <div>
                        <a href="{% url 'blog:blog-home' %}" class="btn-back btn-sm">&laquo; Back to Posts</a>
                    </div>

                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <img src="{{ post.imageURL }}" class="post-thumbnail">

                    <div>
                        {% for category in post.categories.all %}
                            <span class="category">{{ category }}</span>
                        {% endfor %}
                    </div>

                    <hr>

                    <h1 class="post-title">{{ post.title }}</h1>

                    <div class="post-author">
                        <img class="author-pic" src="{{ post.author.profile.profile_pic.url }}">
                        <div>
                            <p class="author-name"><a href="{% url 'blog:user-posts' post.author %}">
                                {{ post.author|upper }}</a></p>
                            <p class="post-date">Posted: {{ post.created|date:"F d, Y" }}</p>
                        </div>
                    </div>

                    <p>{{ post.content|safe }}</p>

                    <div class="comment-section">
                        <div class="row">
                            <h2>Conversation{{ post.postcomment_set.all.count|pluralize }}
                                ({{ post.postcomment_set.all.count }})</h2>

                            <hr class="mb-4">
                            {% if user.is_authenticated %}
                                <form action="" method="post" class="mb-4"> {% csrf_token %}
                                    <div class="form-group mb-3">
                                        <input type="text" class="form-control" id="comment" name="comment"
                                               placeholder="Leave a comment...">
                                    </div>
                                    <button type="submit" class="btn btn-outline-primary btn-sm">
                                        Post Comment
                                    </button>
                                </form>
                            {% else %}
                                <div class="alert alert-warning">
                                    <span class="mx-2 fs-5">
                                        Please <a href="{% url 'login' %}"> Login</a> or
                                        <a href="{% url 'registration' %}"> Create an account</a>
                                        to post a comment.
                                    </span>
                                </div>
                            {% endif %}
                            <hr>

                            {% for comment in post.postcomment_set.all %}
                                <div class="comment">
                                    <img class="author-pic" src="{{ comment.author.profile.profile_pic.url }}">
                                    <div>
                                        <p class="comment-author">
                                            {{ comment.author }}: {{ comment.created|naturaltime }}</p>
                                        <p class="comment-body">{{ comment.comment }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                </div>

                <div class="col-lg-3 right-side-wrapper">
                    <div class="featured-posts">
                        <h4 style="font-weight: 600;"> Featured Posts</h4>
                        <hr>
                        {% for post in posts %}
                            <div class="sidebar-item">
                                <a href="{% url 'blog:post-details' post.slug %}">
                                    <img src="{{ post.imageURL }}">
                                    <div class="sidebar-item-body">
                                        <strong>{{ post.title }}</strong>
                                        <p>{{ post.sub_heading }}</p>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </section>
</main>

{% endblock body %}

blog/templates/blog/post_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<main id="main">
    <section id="post-form" class="post-form">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section-title">
                        <h2> {{ section_title }} </h2>
                    </div>
                    <form method="post" enctype="multipart/form-data"> {% csrf_token %}
                        {{ form.media }}
                        {{ form|crispy }}
                        <button type="submit" class="btn-post-form">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock body %}

blog/templates/blog/user_posts.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<main id="main">
    <section id="blog-post" class="blog-post">
        <div class="container">

            <div class="section-title">
                <h2>Posts by {{ user }}</h2>
            </div>

            <div class="row post-container justify-content-center">

                <div class="col-lg-4 col-md-4">
                    <form id="searchForm" method="GET" class="p-4 bg-light border shadow-sm">
		                {{ my_filter.form|crispy }}

		                <input class="btn btn-outline-primary mt-2" type="submit" value="Search">
	                </form>
                </div>

                <div class="col-lg-8 col-md-8 post-item">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %}
                    {% endif %}

                    {% for post in posts %}
                    <div class="card mb-3 box" style="margin:auto;">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="card-body">
                                    <div class="border-bottom">
                                        <strong class="d-inline-block mb-1 me-2 text-primary">
                                            <a href="{% url 'blog:user-posts' post.author %}">{{ post.author }}</a>
                                        </strong>
                                        <small class="text-muted me-2">{{ post.created|date:"F d, Y" }}</small>
                                        {% if post.author == request.user %}
                                            <a class="btn btn-secondary btn-sm my-1 me-2" role="button"
                                            href="{% url 'blog:post-update' post.slug %}">Update</a>
                                            <a class="btn btn-danger btn-sm my-1" role="button"
                                            href="{% url 'blog:post-delete' post.slug %}">Delete</a>
                                        {% endif %}
                                    </div>
                                    <h3 class="my-2">
                                        <a href="{% url 'blog:post-details' post.slug %}">{{ post.title }}</a>
                                    </h3>
                                    <div class="mb-3">
                                        {% for category in post.categories.all %}
                                            <span class="category">{{ category }}</span>
                                        {% endfor %}
                                    </div>
                                    <p class="article-content">{{ post.sub_heading|truncatechars:300 }}</p>
                                </div>
                            </div>

                            <div class="col-md-4 img-box">
                                <img src="{{ post.imageURL }}" class="card-img" alt="..." height="200px">
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="mt-4">
                        <h3 class="text-center">No Posts available.</h3>
                    </div>
                    {% endfor %}

                    <div class="row my-4">
                        <div>
                            {% include 'blog/pagination.html' %}
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </section>

</main>

{% endblock body %}