Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

admin.site.site_header = "Log in to Shihab's Portfolio"
admin.site.site_title = "Shihab's Portfolio Admin Panel"
admin.site.index_title = "Welcome to Shihab's Portfolio Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),

    path('profile/', user_views.profile, name='profile'),

    path('signup/', user_views.registration, name='registration'),
    path('login/', user_views.login_user, name='login'),
    path('logout/', user_views.logout_user, name='logout'),

    path('password-change/', user_views.password_change, name='password_change'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'),
    #      name='change_password'),
    # path('password-change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
    #      name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('', views.base_home, name='base-home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('inbox/', views.inbox_page, name='inbox'),
    path('message/<str:pk>/', views.message_page, name='message'),
    path('reply/<str:pk>/', views.message_reply, name='message-reply'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.projects, name='projects'),
    path('project/new/', views.project_create, name='project-create'),
    path('project/<slug:slug>/', views.project_details, name='project-details'),
    path('project/update/<slug:slug>/', views.project_update, name='project-update'),
    path('project/delete/<slug:slug>/', views.project_delete, name='project-delete'),
]

projects/models.py
from django.db import models
import uuid
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone


class Tag(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Project(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    content = RichTextUploadingField()
    thumbnail = models.ImageField(upload_to="projects/thumbnails", default='projects/thumbnails/thumbnail.png',
                                  null=True, blank=True)
    created = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('projects:project-details', kwargs={'slug': self.slug})

    # handling empty image field error
    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url

    def save(self, *args, **kwargs):
        if self.slug is None:
            slug = slugify(self.title)

            has_slug = Project.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.title) + '-' + str(count)
                has_slug = Project.objects.filter(slug=slug).exists()

            self.slug = slug
        super(Project, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created']

projects/forms.py
from django import forms
from .models import Project
from ckeditor.widgets import CKEditorWidget


class ProjectForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Project
        fields = ['title', 'content', 'thumbnail', 'active', 'featured', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'tags': forms.CheckboxSelectMultiple(),
        }

projects/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Project, Tag
from .forms import ProjectForm
from .decorators import *


def projects(request):
    all_project = Project.objects.filter(active=True)
    tags = Tag.objects.all()

    category = request.GET.get('q')

    if category is None:
        all_project = all_project
    else:
        category = category.strip()
        all_project = all_project.filter(Q(tags__name__icontains=category))

    context = {'all_project': all_project, 'tags': tags, 'category': category}
    return render(request, 'projects/projects.html', context)


def project_details(request, slug):
    # project = Project.objects.filter(slug=slug).first()
    project = get_object_or_404(Project, slug=slug)

    context = {'project': project}
    return render(request, 'projects/project_details.html', context)


@admin_only
def project_create(request):
    form = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save()
            return redirect('projects:project-details', slug=instance.slug)

    context = {'form': form, 'section_title': 'Add Project'}
    return render(request, 'projects/project_form.html', context)


@admin_only
def project_update(request, slug):
    project = get_object_or_404(Project, slug=slug)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            instance = form.save()
            messages.success(request, f'Project Updated')
            return redirect('projects:project-details', slug=instance.slug)

    context = {'form': form, 'section_title': 'Update Project'}
    return render(request, 'projects/project_form.html', context)


@admin_only
def project_delete(request, slug):
    project = get_object_or_404(Project, slug=slug)

    if request.method == 'POST':
        project.delete()
        messages.success(request, f'Project deleted successfully')
        return redirect('projects:projects')

    context = {'project': project}
    return render(request, 'projects/project_confirm_delete.html', context)

projects/templates/projects/project_confirm_delete.html
{% extends 'base/base.html' %}

{% block body %}

<main id="main">
    <section id="project-delete" class="project-delete">
        <div class="container">

            <div class="section-title">
                <h2>Delete Project</h2>
            </div>

            <div class="row justify-content-center">
                <div class="col-lg-10 p-4 text-center">
                    <form method="post"> {% csrf_token %}
                        <fieldset>
                            <h3>Are you sure you want to delete the project "{{ project.title }}"?</h3>
                        </fieldset>
                        <div class="mt-4">
                            <button class="btn btn-delete me-2" type="submit">Yes, Delete</button>
                            <a class="btn btn-cancel" href="{% url 'projects:projects' %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </section>
</main>

{% endblock body %}

projects/templates/projects/project_details.html
{% extends 'base/base.html' %}

{% block body %}
{% load static %}

<main id="main">
    <section id="project-details" class="project-details">
        <div class="container">
            <div class="row justify-content-center">

                <div class="col-lg-8 border rounded shadow-sm p-4">
                    <div>
                        <a href="{% url 'projects:projects' %}" class="btn-back btn-sm">&laquo; Back to Projects</a>
                    </div>

                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <img src="{{ project.imageURL }}" class="project-thumbnail">

                    <div>
                        {% for tag in project.tags.all %}
                            <span class="tag">{{ tag }}</span>
                        {% endfor %}
                    </div>

                    <hr>

                    <h1 class="project-title">{{ project.title }}</h1>

                    <div class="project-author">
                        <img class="author-pic" src="{% static 'img/profile-image.jpg' %}">
                        <div>
                            <p class="author-name">Shihab Ahmed</p>
                            <p class="post-date">Posted: {{ project.created|date:"F d, Y" }}</p>
                        </div>
                    </div>

                    <p>{{ project.content|safe }}</p>
                </div>

            </div>
        </div>
    </section>
</main>

{% endblock body %}

projects/templates/projects/project_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<main id="main">
    <section id="project-form" class="project-form">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section-title">
                        <h2> {{ section_title }} </h2>
                    </div>
                    <form method="post" enctype="multipart/form-data"> {% csrf_token %}
                        {{ form.media }}
                        {{ form|crispy }}
                        <button type="submit" class="btn-project-form">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock body %}

projects/templates/projects/projects.html
{% extends 'base/base.html' %}
{% block projectsactive %} active {% endblock projectsactive %}

{% block body %}

<main id="main">
    <section id="project" class="project">
        <div class="container">

            <div class="section-title">
                <h2>Projects</h2>
                <p>Here are some of the projects which I have done so far.</p>
            </div>

            <div class="row">
                <div class="col-lg-12 d-flex justify-content-center">
                    <ul id="project-filters">
                        <li class="{% if category is None %}active{% endif %}">
                            <a href="{% url 'projects:projects' %}">All</a>
                        </li>
                        {% for tag in tags %}
                        <li class="{% if tag.name == category %}active{% endif %}">
                            <a href="{% url 'projects:projects' %}?q={{ tag.name }}">{{ tag.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="row project-container justify-content-center">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}

                {% for project in all_project %}
                <div class="col-lg-4 col-md-6 project-item">
                    <div class="card" style="width: 100%;">

                        <div class="project-wrap">
                            <img src="{{ project.imageURL }}" class="card-img-top img-fluid" alt="...">
                        </div>

                        <div class="card-footer py-4">
                            <h5 class="card-text mb-3">
                                <a href="{% url 'projects:project-details' project.slug %}">{{ project.title }}</a>
                            </h5>

                            {% if request.user.is_superuser %}
                            <div class="mb-3">
                                <a href="{% url 'projects:project-update' project.slug %}"> Edit </a> |
                                <a href="{% url 'projects:project-delete' project.slug %}"> Delete </a>
                            </div>
                            {% endif %}

                            <div class="border-top">
                                {% for tag in project.tags.all %}
                                    <span class="tag mt-3">{{ tag }}</span>
                                {% endfor %}
                            </div>

                        </div>

                    </div>
                </div>

                {% empty %}
                <div class="mt-4">
                    <h3 class="text-center">No projects available.</h3>
                </div>
                {% endfor %}

            </div>

        </div>
    </section>
</main>

{% endblock body %}