Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

admin.site.site_header = "Log in to Shihab's Portfolio"
admin.site.site_title = "Shihab's Portfolio Admin Panel"
admin.site.index_title = "Welcome to Shihab's Portfolio Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),

    path('profile/', user_views.profile, name='profile'),

    path('signup/', user_views.registration, name='registration'),
    path('login/', user_views.login_user, name='login'),
    path('logout/', user_views.logout_user, name='logout'),

    path('password-change/', user_views.password_change, name='password_change'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'),
    #      name='change_password'),
    # path('password-change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
    #      name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('', views.base_home, name='base-home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('inbox/', views.inbox_page, name='inbox'),
    path('message/<str:pk>/', views.message_page, name='message'),
    path('reply/<str:pk>/', views.message_reply, name='message-reply'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_home, name='blog-home'),
    path('post/new/', views.post_create, name='post-create'),
    path('user/<str:username>/', views.user_posts, name='user-posts'),
    path('post/<slug:slug>/', views.post_details, name='post-details'),
    path('post/update/<slug:slug>/', views.post_update, name='post-update'),
    path('post/delete/<slug:slug>/', views.post_delete, name='post-delete'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.projects, name='projects'),
    path('project/new/', views.project_create, name='project-create'),
    path('project/<slug:slug>/', views.project_details, name='project-details'),
    path('project/update/<slug:slug>/', views.project_update, name='project-update'),
    path('project/delete/<slug:slug>/', views.project_delete, name='project-delete'),
]

base/models.py
from django.db import models
import uuid


class Skill(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    knowledge = models.IntegerField(default=0)
    body = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-knowledge']


class Certificate(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    organization = models.CharField(max_length=255)
    category = models.CharField(max_length=100)
    url = models.URLField(max_length=500)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['category']


class Contact(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=300)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}, {self.email} at {self.created}'

    class Meta:
        ordering = ['is_read', '-created']

base/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'name@example.com'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Message',
                                             'rows': 6}),
        }

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from .models import Skill, Contact, Certificate
from .forms import ContactForm
from .decorators import *

from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings


def base_home(request):
    message = Contact.objects.filter(is_read=False).count()
    request.session['messages'] = message
    context = {}
    return render(request, 'base/base_home.html', context)


def about(request):
    skills = Skill.objects.all()
    certificates = Certificate.objects.all()
    context = {'skills': skills, 'certificates': certificates}
    return render(request, 'base/about.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, f"Thanks for contacting. I'll try to contact you back as soon as possible.")
            return redirect('base:contact')
    else:
        form = ContactForm()
    context = {'form': form}
    return render(request, 'base/contact.html', context)


@admin_only
def inbox_page(request):
    inbox = Contact.objects.all()

    request.session['messages'] = Contact.objects.filter(is_read=False).count()

    context = {'inbox': inbox}
    return render(request, 'base/inbox.html', context)


@admin_only
def message_page(request, pk):
    message = get_object_or_404(Contact, id=pk)
    message.is_read = True
    message.save()

    context = {'message': message}
    return render(request, 'base/message.html', context)


@admin_only
def message_reply(request, pk):
    message = get_object_or_404(Contact, id=pk)

    if request.method == 'POST':

        template = render_to_string('base/email_template.html',
                                    {'name': request.POST.get('name'),
                                     'reply': request.POST.get('reply')})

        email = EmailMessage(request.POST.get('subject'),
                             template,
                             settings.EMAIL_HOST_USER,
                             [request.POST.get('email')])

        email.fail_silently = False
        email.send()

        messages.success(request, 'Email sent successfully!')
        return redirect('base:message', pk=message.id)

    context = {'message': message}
    return render(request, 'base/message_reply.html', context)

base/templates/base/403_forbidden.html
<!DOCTYPE html>
<html lang="id" dir="ltr">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <title>Sorry, This Page Can&#39;t Be Accessed</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <style type="text/css">
        html, body {
            height: 100%;
        }

        #page-wrapper {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
        }

        #success-box {
            max-width: 800px;
            height: auto;
            border:1px solid #888;
            border-radius: 5px;
            background: #e9e8e6;
            padding: 15px;
        }

        #success-box p {
            font-size: 18px;
        }

        #success-box .btn-back {
            font-weight: 600;
            font-size: 16px;
            padding: 10px 30px 12px 30px;
            border: 0;
            border-radius: 50px;
            transition: 0.5s;
            margin-top: 10px;
            color: #fff;
            background: #dc3545;
        }

        #success-box .btn-back:hover {
            background: #c51b2c;
        }
    </style>
</head>

<body class="bg-dark">

    <div id="page-wrapper">
        <div id="success-box" class="content-block">
            <div class="row">
                <div class="col-lg-2 text-center">
                    <p><i class="fa fa-exclamation-triangle fa-5x"></i><br/>Status Code: 403</p>
                </div>
                <div class="col-lg-10 text-center">
                    <h3>OPPSSS!!!! Sorry...</h3>
                    <p>Sorry, your access is denied due to security reasons of our server.
                        <br/>Please go back to the previous page to continue browsing.</p>
                    <a class="btn btn-back" href="javascript:history.back()">Go Back</a>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

base/templates/base/about.html
{% extends 'base/base.html' %}
{% block aboutactive %} active {% endblock aboutactive %}

{% block body %}
{% load static %}
<main id="main">
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        <div class="container" data-aos="zoom-in" data-aos-delay="100">

            <div class="section-title">
                <h2>About</h2>
                <p>I'm a Back-End Developer located in Sylhet, Bangladesh.</p>
                <p>Well-organised person, problem solver.</p>
                <p>Fan of English movie and TV series.</p>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <img src="{% static 'img/Shihab.jpg' %}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-8 pt-4 pt-lg-0 content">
                    <h3>Web Developer (Backend Developer / Django Expert)</h3>
                    <p class="fst-italic">
                        Well-organised person and passionate problem solver with 2+ years of experience in Python and
                        6+ months of experience in Back-End Development using Django.
                    </p>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul>
                                <li><i class="bi bi-chevron-right"></i> <strong>Name:</strong>
                                    <span>Shihab Ahmed</span></li>
                                <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>22</span></li>
                                <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong>
                                    <span>+880 1772 432557</span></li>
                                <li><i class="bi bi-chevron-right"></i> <strong>City:</strong>
                                    <span>Sylhet, Bangladesh</span></li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul>
                                <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong>
                                    <span>25 September 1998</span></li>
                                <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong>
                                    <span>B.Sc. Engineering in ICT</span></li>
                                <li><i class="bi bi-chevron-right"></i> <strong>Email:</strong>
                                    <span>shihab.ict.cou@gmail.com</span></li>
                                <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong>
                                    <span>Available</span></li>
                            </ul>
                        </div>
                    </div>
                    <p>Visit my <a href="https://linkedin.com/in/shihab-ahmed-7861b5138" class="linkedin"
                                   target="_blank">LinkedIn</a> profile for more details or just
                        <a href="{% url 'base:contact' %}">contact</a> me.
                    </p>
                </div>
            </div>

        </div>
    </section>

    <!-- ======= Education Section ======= -->
    <section id="education" class="education">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Education</h2>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <div class="education-item">
                        <h4>Masters of Sciences (Engg.) in Information and Communication Technology</h4>
                        <h5>2019 - 2020</h5>
                        <p><em>Comilla University, Cumilla, Bangladesh</em></p>
                        <p>Result: CGPA /4.00</p>
                    </div>
                    <div class="education-item">
                        <h4>Bachelor of Sciences (Engg.) in Information and Communication Technology</h4>
                        <h5>2015 - 2019</h5>
                        <p><em>Comilla University, Cumilla, Bangladesh</em></p>
                        <p>Result: CGPA 3.79/4.00</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="education-item">
                        <h4>Higher Secondary Certificate (HSC)</h4>
                        <h5>2013 - 2015</h5>
                        <p><em>Urea Sar Karkhana College, Narsingdi, Dhaka</em></p>
                        <p>Result: GPA 4.92/5.00</p>
                    </div>
                    <div class="education-item">
                        <h4>Secondary School Certificate (SSC)</h4>
                        <h5>2002 - 2013</h5>
                        <p><em>Palash Sar Karkhana High School, Narsingdi, Dhaka</em></p>
                        <p>Result: GPA 5.00/5.00</p>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <!-- ======= Skills Section ======= -->
    <section id="skills" class="skills">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Skills</h2>
            </div>

            <div class="row skills-content">
                {% for skill in skills %}
                    <div class="col-lg-6">
                        <div class="progress">
                            <span class="skill">{{ skill.name }} <i class="val">{{ skill.knowledge }}%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" style="width: {{ skill.knowledge }}%" aria-valuenow="{{ skill.knowledge }}"
                                     aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </section>

    <!-- ======= Certificates Section ======= -->
    <section id="certificates" class="certificates">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Certificates</h2>
            </div>

            <div class="row mb-3">
                {% for certificate in certificates %}
                <div class="col-lg-6">
                    <div class="certificate-item pb-0">
                        <h4>{{ certificate.name }}</h4>
                        <p><strong>Issuing organization:</strong> {{ certificate.organization }}</p>
                        <p><strong>Credential URL:</strong> <a href="{{ certificate.url }}" target="_blank">
                            View Certificate</a></p>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row mb-3">
                {% endif %}
                {% endfor %}
            </div>

        </div>
    </section>
</main>

{% endblock body %}

base/templates/base/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Files-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% if title %}
    <title> Shihab - {{ title }} </title>
    {% else %}
    <title> Shihab | Back End Developer | Django Expert </title>
    {% endif %}

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <style>{% block css %} {% endblock css %}</style>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light py-3 fixed-top">
        <div class="container-fluid">
            <h1 class="logo me-auto me-lg-0"><a href="{% url 'base:base-home' %}">Shihab</a></h1>
            <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a href="{% url 'base:base-home' %}"
                                            class="{% block homeactive %} {% endblock homeactive %}">Home</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'base:about' %}"
                                            class="{% block aboutactive %} {% endblock aboutactive %}">About</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'projects:projects' %}"
                                            class="{% block projectsactive %} {% endblock projectsactive %}">Projects</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'blog:blog-home' %}"
                                            class="{% block blogactive %} {% endblock blogactive %}">Blog</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'base:contact' %}"
                                            class="{% block contactactive %} {% endblock contactactive %}">Contact</a>
                    </li>

                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <strong class="text-dark">Hello, {{ request.user }}</strong>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'profile' %}">Settings</a></li>

                            {% if request.user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'base:inbox' %}">
                                Messages ({{ request.session.messages }})</a></li>
                            <li><a class="dropdown-item" href="{% url 'projects:project-create' %}">Add Project</a></li>
                            {% endif %}

                            <li><a class="dropdown-item" href="{% url 'blog:post-create' %}">Add Post</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:user-posts' request.user %}">
                                View Your Posts</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
                        </ul>
                    </li>
                    {% endif %}

                </ul>

                {% if request.user.is_authenticated %}
                <div class="d-flex header-social-links">
                    <a href="https://twitter.com/im_Shihab_Ahmed" class="twitter" target="_blank">
                        <i class="bi bi-twitter"></i></a>
                    <a href="https://www.facebook.com/ShihabAhmedApu/" class="facebook" target="_blank">
                        <i class="bi bi-facebook"></i></a>
                    <a href="https://www.instagram.com/shihab_ahmed09/" class="instagram" target="_blank">
                        <i class="bi bi-instagram"></i></a>
                    <a href="https://linkedin.com/in/shihab-ahmed-7861b5138" class="linkedin" target="_blank">
                        <i class="bi bi-linkedin"></i></a>
                </div>
                {% else %}
                <div class="d-flex">
                    <a href="{% url 'login' %}" class="me-1"> Login</a> /
                    <a href="{% url 'registration' %}" class="ms-1 me-4">Sign Up </a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

{% block body %} {% endblock body %}

{% block footer %} {% endblock footer %}

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center">
    <i class="bi bi-arrow-up-short"></i></a>

<script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
        integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block js %} {% endblock js %}

</body>
</html>

base/templates/base/base_home.html
{% extends 'base/base.html' %}
{% block homeactive %} active {% endblock homeactive %}

{% block body %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
    <div class="container d-flex flex-column align-items-center" data-aos="zoom-in" data-aos-delay="100">
        <h1>Shihab Ahmed</h1>
        <h2>I'm a web developer (Backend Developer / Django Expert)</h2>
        <a href="{% url 'base:about' %}" class="btn-about">About Me</a>
    </div>
</section>

{% endblock body %}

{% comment %}
{% block footer %}
{% include 'base/footer.html' %}
{% endblock footer %}
{% endcomment %}

base/templates/base/email_template.html
Hello {{name}},

Thanks for reaching me out.

{{reply}}

Regards,
Shihab Ahmed

base/templates/base/footer.html
<footer id="footer">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Shihab</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Design idea taken from <strong><span>BootstrapMade</span></strong> and
            edited by <strong><span>Shihab</span></strong>
        </div>
    </div>
</footer>

base/templates/base/inbox.html
{% extends 'base/base.html' %}

{% block body %}

<main id="main">
    <section id="resume" class="resume">
        <div class="container">

            <div class="section-title">
                <h2>My Messages</h2>
            </div>

            <div class="row">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Sender</th>
                            <th scope="col">Subject</th>
                            <th scope="col">Data Sent</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for message in inbox %}
                            {% if message.is_read %}
                        <tr>
                            {% else %}
                        <tr style="font-weight: 800;">
                            {% endif %}
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ message.name }}</td>
                            <td><a href="{% url 'base:message' message.id %}">
                                {{ message.subject }}</a></td>
                            <td>{{ message.created }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </section>
</main>

{% endblock body %}

base/templates/base/message.html
{% extends 'base/base.html' %}

{% block body %}

<main id="main">
    <section id="resume" class="resume">
        <div class="container">

            <div class="section-title">
                <h2>{{ message.subject }}</h2>
            </div>

            <div class="row justify-content-center">
                <div class="col-lg-8">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="mb-4">
                        <a href="{% url 'base:inbox' %}" class="btn btn-secondary btn-sm me-2">&laquo; Go back to inbox</a>
                        <a href="{% url 'base:message-reply' message.id %}" class="btn btn-primary btn-sm">Reply &raquo;</a>
                    </div>

                    <p><strong>Name:</strong> {{ message.name }}</p>
                    <p><strong>Email:</strong> {{ message.email }}</p>
                    <p><strong>Sent:</strong> {{ message.created }}</p>
                    <hr>
                    <p>{{ message.subject }}</p>
                </div>
            </div>

        </div>
    </section>
</main>

{% endblock body %}

base/templates/base/message_reply.html
{% extends 'base/base.html' %}

{% block body %}

<main id="main">
    <section id="resume" class="resume">
        <div class="container">

            <div class="section-title">
                <h2>Replying to: {{ message.name }}</h2>
            </div>

            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="mb-4">
                        <a href="{% url 'base:inbox' %}" class="btn btn-secondary btn-sm me-2 mb-4">&laquo; Go back to inbox</a>
                    </div>

                    <form method="post">  {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" class="form-control" name="name" value="{{ message.name }}" hidden>
                            <input type="email" class="form-control" name="email" value="{{ message.email }}" hidden>
                            <input type="text" class="form-control" name="subject" value="{{ message.subject }}" hidden>

                            <label for="reply" class="form-label">Write your reply here</label>
                            <textarea class="form-control" id="reply" name="reply" rows="5" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary mt-2">Send Message</button>
                    </form>
                </div>
            </div>

        </div>
    </section>
</main>

{% endblock body %}